### ISSUE TITLE
G1000nxi panels not working?

### ISSUE THREAD

**Issue by s4admin** [Simstrumentation/Air-Manager#13]
I'm unable to get most of the buttons on the G1000nxi buttons to work in fs2020.  the altitude bug works but nearly everything else does not, like the flight plan or direct to button.  Is there something else needed to make it work?

**Comment by s4admin** [comment]
updated the air manager plugin and now it's all working... sorry !  all good.

**Comment by hairy-dog** [comment]
It would be so helpful if there were visible plugin version numbers. I just update from time to time just in case there's a new one. How am I supposed to know?

**Comment by rob2791** [comment]
I agree, there is no way for us to know. We'll recommend that to the devs of AM.
