### ISSUE TITLE
PMS50 GTN 650 overlay 

### ISSUE THREAD

**Issue by dapperAWS** [Simstrumentation/Air-Manager#16]
Having issues getting the PMS50 GTN650 overlay to actually show on my panel.  The instrument shows properly in AM config (has preview).  I can see the resource folder where the images are called, however when I show the panel, the instrument is blank.

I feel like this instrument was working for me before the latest update, however I am not 100% sure as I only recently started using the GTNs.

**Comment by dapperAWS** [comment]
I figured out where the issue is:
line 136
button_add(nil, nil, , inner_pos[1], inner_pos[2], inner_pos[3], inner_pos[4], function()

should be

button_add(nil, nil, inner_pos[1], inner_pos[2], inner_pos[3], inner_pos[4], function()

**Comment by Crunchmeister1** [comment]
Fixed. Turns out the version I was using and testing on was newer than the one on GitHub and the error was fixed. That's why I was unable to recreate it on my end. 

Should all be working now.
