### ISSUE TITLE
Garmin G3X nearest button

### ISSUE THREAD

**Issue by Gascrich** [Simstrumentation/Air-Manager#17]
Hi
I am working on an overlay for the G3X for MSFS. I was able to activate most of the events, but not the Nearest.
I found on Ghub a similar project, with the same event I'd used.
I have not tried this script, but can someone tell me if there is a change in MSFS, which would invalidate this Id.
Thanks in advance

**Comment by rob2791** [comment]
@Gascrich is there something wrong with the G3X that's in our Github? https://github.com/Simstrumentation/Air-Manager/tree/main/Instruments/Generic/Generic-Garmin-G3X

What plane are you trying to get it to work on?
And just for reference, are you on the MSFS2020 Beta Avionics update or just regular sim no Beta testing?

**Comment by Gascrich** [comment]
Hi rob2791,
Thank you for replying to my request.
Since my post, I downloaded the instrument "Generic-Garmin_G3X" from GitHUb  and tested it on my system. I have the latest update of MSFS and version 4.1.5 of Air Manager. Not the beta.
I use it on the CubCrafters X Cub.
**I have to say that it is working well. Great**
After comparing with my work, I realized that my event call was not the same as the GitHub version. I used the event named _"H:AS3X_Touch_1_Nearest_Push"_, which was exactly the name used in the <Dev mode, Behaviors, InputEvents, AS3X, AS3X _Touch_1_Nearest>.
After changing to the GitHub event name (NRST), everything is working well.
Unfortunately, I found other events like the barometric (Inc Dec) that are not working when I try to use the name shown in Dev mode. I also tried the name available in the shared aircraft list, but it not working.
Can someone indicate me where I can have an up-to-date list that I can rely on for my future projects?
Or is there a way to monitor the events to get the good names?
Thanks' in advance
Richard

**Comment by rob2791** [comment]
Good to hear!
The bad news is there isn't a single source that has all the variables. That's what takes so much time and dedication is figuring out what variables work and what doesn't work. For most things, i highly recommend MobiFlight. It's a middle man that is open source and allows the entire community to enter in RPN (MSFS's native language) and takes all the leg work out of it by putting usually assembling it into 1 variable to call. There's plenty of documentation around about Mobiflight and AM. But once you install MobiFlight, it puts a WASM module into your MSFS directory and you can just call the events in AM by doing something like    _fs2020_event("MOBIFLIGHT.Generic_Upr_Push_PFD_MENU")_
All of the mobiflight's events are in what we call "HubHop". You can browse the list to see if what you want is here: https://hubhop.mobiflight.com/#/list

For anything that we publish for the community, we don't use MobiFlight (but use HubHop to look up events all the times). Were usually stuck reading the RPN code in Dev mode to figure out what it does. For generic events, the MSFS SDK has plenty of variables. You can get to it here: https://docs.flightsimulator.com/html/Programming_Tools/SimVars/Simulation_Variables.htm

I'll close this out, but make sure you're a member of our discord server for easy chatting. 
Cheers!
