### ISSUE TITLE
Auto Pilot

### ISSUE THREAD

**Issue by juyttewaal** [Simstrumentation/Air-Manager#18]
Hi, I keep having a problem with the VNV button on the autopilot instrument which doesn’t want to engage until the plane has reached TOD. But maybe it’s normal?
Thanks for your great work.

**Comment by rob2791** [comment]
@juyttewaal which instrument are you referring too?

**Comment by juyttewaal** [comment]
![4AF3E1FC-FC2E-43AC-B05C-92A91CBB9562](https://user-images.githubusercontent.com/79478405/209598463-d8864cef-2459-4745-895c-5ad3fdcda10a.png)

**Comment by juyttewaal** [comment]
Sorry, I must have closed this inadvertently. Above is the instrument in question.

**Comment by Crunchmeister1** [comment]
What plane are you having issues with specifically? If it's the Vision Jet, there are currently issues with VNAV and it doesn't work quite right from this AP atm. 

If it's other planes, please be specific.

**Comment by juyttewaal** [comment]
Sorry I am just back. Yes, it was for the Vision, VNAV seemed to engage only from the cockpit, and not from the instrument above.  I see you confirmed above, so thank you.

**Comment by Crunchmeister1** [comment]
This now works correctly with the most recent version in the Vision Jet.
