### ISSUE TITLE
Using your project files for personal project?

### ISSUE THREAD

**Issue by sadu** [Simstrumentation/Air-Manager#19]
Hello, I am not an Air Manager user. Is it okay if I download and use your assets, specifically the CJ4 ones in my personal app?

I am developing a web based cockpit for the CJ4 completely from scratch using node-simconnect + websockets + react and would like to use your panel assets for building the UI - this is perfectly in line with what I had in mind(just to control the AP alt and heading) and you guys seem to have done it and beyond!

My app at present is entirely for personal use and not distributed anywhere, since the repo did not have any license info I thought of asking here.

Thanks and I really appreciate the work done here!

**Comment by rob2791** [comment]
Sadu,
Thanks for the thoughtfulness of asking, We really appreciate it. Our work is in the public domain, so you are free to use it. 
Since it's for personal use it's not a big deal, but if you wish to freely publish your work (and I would encourage you too!), a statement of credit in for the work would be appreciated. 

Cheers,
Rob

**Comment by Crunchmeister1** [comment]
I would encourage you to share it when you finally get it complete. There would be a lot of people who don't use Air Manager who could benefit from it as well. 

In any case, like Rob said, you're free to use it as it's public domain. A credit for using the stuff is appreciated if you do share it publicly.

**Comment by sadu** [comment]
Sure, I am eagerly waiting for the avionics update to get everything in order. Using SimConnect alone is proving to be challenging because of the restrictions it impose on the different type of variables.

Thanks a lot, will ping you again if the project ever goes public!
