### ISSUE TITLE
Rockwell Collins FMS Not Transparent

### ISSUE THREAD

**Issue by selsamman** [Simstrumentation/Air-Manager#21]
When I first start using this FMS in February there was a transparent cutout to view the pop-out.  Now it appears to be black.  Toggling transparent in Air Manager shows the area around the four corners where there is a cutout for the screws as transparent but not the screen part in the middle.  I haven't changed anything in my setup and and having difficulty understanding why this is suddenly the case.  Using version 2.2 and tried deleting and re-downloading the instrument.

**Comment by IanBevvo** [comment]
Hi,
I'm having the exact same issue, in fact this was working Fri/Sat when I first installed it, but today (Sunday) I'm seeing the same black areas of the Rockwell and FMS. Also tried deleting and re-downloading etc
Would love to get this fixed, as the instruments are very good.

**Comment by selsamman** [comment]
I believe this is because the variable "CIRCUIT ON:47" has changed meaning in some FS2020 update.  
```
--Backgroud Image 
screenoff = img_add("display_off.png", 70, 50, 600, 600)
```
...

```
function ss_screenpower(Cir47)
        if Cir47== true then
            visible(screenoff, false)
        else
            visible(screenoff, true)
        end        
end
fs2020_variable_subscribe(
                          "CIRCUIT ON:47","bool", ss_screenpower)
```

Until this is fixed I simply commented out the img_add of the display_off image and the subscription to the CIRCUIT ON variable.

```
--Backgroud Image 
--screenoff = img_add("display_off.png", 70, 50, 600, 600)
```

...

```
--fs2020_variable_subscribe( "CIRCUIT ON:47","bool", ss_screenpower)
```

 Now it works properly though it won't switch to black when you power off the plane.

**Comment by IanBevvo** [comment]
Thanks for the response @selsamman  very much appreciated. I'll copy the instrument and make the change.
Thanks again, Ian.

**Comment by rob2791** [comment]
Well that's bizarre, it works fine for me tonight??
I have zero explanation!

**Comment by selsamman** [comment]
Was that after the latest FS update?  It's possible that circuit 47 (power for the display) got broken in one update and fixed in another.
