### ISSUE TITLE
Black panel

### ISSUE THREAD

**Issue by MarceloGatinho** [Simstrumentation/Air-Manager#22]
Air manager works with default instruments, but, with all instruments downloaded from here i got black panel. What im doing wrong?

**Comment by Flintstone2k12** [comment]
Same here. I tried Cessna 310 and TBM 930 but got a black screen, apart from the default instruments. This only happens when using the Air Player on a second PC. The same panels works OK when put on a directly attached screen to Air Manager. So what causes this? Some code missing in the instrument/panel scripts?

Wilfried (Flintstone2K12)

**Comment by Flintstone2k12** [comment]
Found the solution to my problem!
In Air Manager go to Create/Edit, select Air Player (must be connected), Select all downloaded/custom instruments and click Push (see attached picture). This uploads the necessary resources to the AP running remote.

Wilfried

![image](https://github.com/Simstrumentation/Air-Manager/assets/82069745/5f594650-3c92-40f3-9890-f20d74a42858)

**Comment by MarceloGatinho** [comment]
i will try it! thx

**Comment by TimothyH97** [comment]
I seem to be having the same issue when using the default CJ 4 in MSFS 2020 on PC. All display screens are black on my air manager panel but other switches and buttons work including the landing gear lever.  What was the resolution to this issue? Thanks in advance.

air manager 4.1.6

**Comment by TimothyH97** [comment]
> Found the solution to my problem! In Air Manager go to Create/Edit, select Air Player (must be connected), Select all downloaded/custom instruments and click Push (see attached picture). This uploads the necessary resources to the AP running remote.


I did try this but to no avail.
