### ISSUE TITLE
Imported SI Panels not showing in Air Manager...

### ISSUE THREAD

**Issue by texaszman** [Simstrumentation/Air-Manager#23]
Downloaded files for SF50 and Honda Jet, including the 3000/5000 panel, imported via Air Manager one by one, says success and installed but do NOT show in Air Manager when I go to create a new panel.  Have repeated with new install - still no imported panels or bezels showing in Air Manager.

Searched for an answer but no luck.  Am I doing something wrong by just importing the .siff files?  Thank You.

**Comment by Crunchmeister1** [comment]
Are you still experiencing this issue?
