### ISSUE TITLE
Duke Air manger Gauges

### ISSUE THREAD

**Issue by KilstormMcBride** [Simstrumentation/Air-Manager#27]
I read that you might be in the works for creating air manager gauges for the Black Square Dukes. If this is the case, how is the project coming along?

**Comment by rob2791** [comment]
@KilstormMcBride Yes, one of our members, Todd, is creating the Duke panels. The best place to follow is the Discord, he's posted some screen shots in #work-in-progress thread. Check it out here: https://discord.gg/6xkCXe5pMn
