### ISSUE TITLE
Download error 

### ISSUE THREAD

**Issue by javandper** [Simstrumentation/Air-Manager#28]
E
![Error](https://github.com/user-attachments/assets/2adac79f-f47d-4225-9e3a-7cfb2fac0097)
Error loading  page

**Comment by rob2791** [comment]
SimInnovations is in the process of bringing all of our Simstrumentation GitHub instruments into the AirManager store for (free) easy downloading in the next release of AirManager (AM5). They will be compatible with MSFS2020 and 2024 natively. Estimated release date is February 2025. Everything should get fixed then.
