### ISSUE TITLE
gtc580 knobster and airmanager

### ISSUE THREAD

**Issue by dpantoleon** [Simstrumentation/Air-Manager#29]
thank you for the gtc580 overlay for airmanager
i have knobster enabled and connected , I can manipulate with mouse (have setting touch and mouse) but nothing happens with the knobster
i tried a g1000 and saw that when you touch a knob it becomes active (orange) and then by using the knobster you turn the dial
what am i doing wrong?
same thing happens with the gtc500 HDG bug and alts sel are not responding to touch only mouse (thankfully i dont need them as i have some old goflight mcp module and using that )
i belive its an airmanager knobster issue but trying to get help from anywhere i can
itd been a great experience using gtc580 and autopilot wth touch control on my touch screen and it is just missing the knobs so i can be almost mouse free
thank you in advance

**Comment by rob2791** [comment]
Hi @dpantoleon ,
Did you assign the knobster to your gtc580 panel? You are able to get it to work with the g1000 correct?

**Comment by dpantoleon** [comment]
The panel shows knobster enabled and no it is not working with the g1000nxi either nor the g1000 default so most probaply its a lnobster issue that i cant figure out...just dont know how to troubleshoot it

**Comment by dpantoleon** [comment]
Managed to get everything working with airmanager (g1000 and gtc580 as well)after fresh install of air manager...Thank you for your panel for gtc580 they work great...vision jet mouse free flying is a blast!!!!
 just a couple of things 
Vnav on autopilot g500 panel does not respond when touching on my touch screen (nor does it respond on my streamdeck mkII) only works inside the cockpit with the mouse use(is there something im doing wrong and needs a parameter to be activated?i go fd ap nav and vnav enabled on the gtc580) i can even push vnav on the ground via mouse and goes from off to on...so any ideas???
And is there a panel to simulate the checklist scroll in vision jet?
Again thank you so much for your contribution

**Comment by rob2791** [comment]
@dpantoleon I'm not sure about checklist in visionjet, that's not something we do.
Our Discord is the best place for help.
