### ISSUE TITLE
SF50 Instruments don't work with MSFS 2024

### ISSUE THREAD

**Issue by Vandalay1125** [Simstrumentation/Air-Manager#31]
I have almost all the SF50 Vision Jet instruments on panels including the generic Garmin stuff and none of it seems to work with 2024. I have the Air Manager Beta 5 and the updated plugins and I can use other instruments with 2024 successfully via Air Manager.

**Comment by cdrage** [comment]
(Most) of it works for me after a few hours of flying, but here are the ones that **ARE NOT** working (after swapping the fs2020 variable for msfs_).

- [ ] OFF / RUN engine button
- [ ] Master Oxygen button
- [ ] Fresh air button
- [ ] Fuel control (cannot turn to left auto or right)
- [ ] Landing light toggles (briefly goes on and then off)
- [ ] Light for AT does not turn on

**Comment by rob2791** [comment]
SimInnovations is in the process of bringing all of our Simstrumentation GitHub instruments into the AirManager store for (free) easy downloading in the next release of AirManager (AM5). They will be compatible with MSFS2020 and 2024 natively. Estimated release date is February 2025. In the mean time, several others have already git forked our repo and converted some instruments for MSFS2024, you'll find links to them in the chat on discord, or by looking at the forks of this repo.

We will most likely stop using this Github, and submit them right to AirManager.
