### ISSUE TITLE
Daher Kodiak Fuel Valve not working

### ISSUE THREAD

**Issue by Onthemarks** [Simstrumentation/Air-Manager#9]
Want to start off by saying I am new to using Air Manager and have limited programming experience. Very excited to find you GitHub page and the instruments you are creating are awesome. I downed the Daher Kodiak fuel valve but I am unable to get it working. Currently I am running Air Manager 4.02 with plug-in 3.7. Just want to confirm all I need to do is input the .siff instrument file and then add to my panel. When I click on Fuel valve graphic is not updating or changing gauge in MSFS. I suspect I am having other issues as I also can not get your Garmin G1000 NXI working. Currently I’m using the generic G1000 Overlay for FS2020 with Air Manager 4.02 and the 3.7 plug-in with no issues. I also have a lot of hardware mappings setup to switches, etc and that is all working fine. With my limited knowledge I suspect I am doing something really simple wrong. Any help you have would appreciate it.

**Comment by Crunchmeister1** [comment]
I'm not sure what could be causing you issues with the fuel valves. I've used them quite often, as have others, and no reports of issues.

Same with the G1000 NXi. I can offhand name at least a dozen people using it without issue. I'm not sure why it wouldn't be working but the default AM one would. Both bezels are sending the exact same commands to Air Manager. 

"Not working" is pretty broad though. What exactly isn't working?

**Comment by Onthemarks** [comment]
Thanks for the reply. So it should work fine with Air Manager 4.02 and 3.7 plug-in? All I need to do is upload the .siff instrument file and then add instrument to my panel? Another thought I had was to save the latest version of the mobiflight-event-module in my community folder. I will check a few more things tonight to see if I can get it going.

**Comment by Onthemarks** [comment]
I also tried the Kodiak Light and Ice panel and certain switches are working and others are not. I need to check and see which ones are not functioning. I’m also using the the generic G1000 Overlays with 2 IPADS and that is working fine except for a few buttons like VNAV. I will do some more troubleshooting tonight.

**Comment by Onthemarks** [comment]
Was playing around with it tonight. For the fuel valve nothing is working.  For the  switch panel the Master, Avionics bus, generator, alternator work, and nothing else. For the G1000 NXI nothing works. When I run the Generic G1000 it works fine. I noticed for the events the Generic G1000 used mobiflight. Not sure if maybe that is a clue of what the issue is?

**Comment by Crunchmeister1** [comment]
MObiflight is more than a clue. It's a smoking gun. If your G1000 is using Mobiflight events, that's not our current Simstrumentation G1000 NXi. The old G1000 that used Mobiflight events was back in August. The current V2.1 was released Oct 21. It doesn't replace old versions in existing panels you may have. It's a completely new instrument altogether. 

I would recommend you completely remove any current G1000 bezels you have in Air Manager (other than the default AM one) and download the latest. You'll then have to re-add that new NXi bezel to your existing panels. The new version uses all the same standard SimConnect events as the Sim Innovations default G1000. If the default works, ours should also work if you have the right version. Ours has a few added features over the default one like working volume knobs, correct behaviours of Nose Up / Down depending on the mode (VS or FLC), and VNAV works if you're using the WT G1000 NXi. Otherwise it's all the same events and variables. And it's got updated graphics that make it look like a modern G1000 NXi vs looking like a 15 year old base model. Those are the differences.

As for the Kodiak fuel valves and certain commands for the switch panel not working, that leads me to believe you don't have plugin 3.7 running as you think you have. Version 3.7 added support for reading and writing of L: variables, which wasn't possible with older versions of the plugin. The Kodiak fuel valves run exclusively on L: variables. That's the way SWS built the Kodiak. Most of the electrical switch panel also runs on custom L: vars except for the master, avionics and alternators, which use standard SimConnect events and variables. THat would explain why those few switches work for you, but not the others that use L: vars.

So it's either you're not actually running plugin 3.7 as you think you are, or there's something wrong with your install of Air Manager.

**Comment by Onthemarks** [comment]
Glad that clue was a smoking gun 😀. As far as I know I'm definitely running Air Manager 4.02 and the 3.7 plug. I am going to uninstall everything and reinstall again. I just want to confirm I don't need to load the Beta 4.1 with the 3.8 beta plugin. Was not sure if there were added features in the beta plug-in that were required. Really want to get your G1000 NXI instrument working as it looks great and has the added features. Also the Kodiak by far is my favorite MSFS2020 aircraft and I'm excited to see what instruments you create. Thanks again for all your help.

**Comment by Crunchmeister1** [comment]
I don't know how to check for the version of the plugin, but I have the latest non-beta version and AM 4.02. 

Not sure why you wouldn't be able to see L: vars of the Kodiak panels if you have the latest version of the plugin. I know it's not our instruments. Like literally, out of the dozens of downloads we've had so far on the Kodiak, you're the 1 singular case  where it's not working. Seeing as how the normal SimConnect events work, but L: vars don't and that L:var support was added in 3.7, it leads me to believe that you have an older plugin running.

As for the G1000 NXi, it should run on any version of the plugin that runs the default AM G1000, as it uses nothing out of the ordinary.

**Comment by Onthemarks** [comment]
Good to know. Let me try a few more things. I am also going to look at the connector log file and see if there are any clues there.

**Comment by Onthemarks** [comment]
Got it all working!! You actually led me down the right path with your comments here and also on Sim Innovations forum. You made post on that forum about issues with FS2020 bridge services stopping and needed to reload bridge or restart service. Then I saw posts  about installing bridge and airplugin folder not installed to the correct community folder. In the end that ended up being my problem. I purchased MSFS2020 on Steam and my community folder was in a different location compared to where install was putting it. I copied the folder to the correct location and everything now work great!! I also installed the Beta version of Air Manger 4.1 and the beta 3.8 plug-in. Can’t wait to get the Kodiak in the air with your fuel valve, switch panel, and G1000 NXI overlay. Thanks for all your help, really appreciate it!!

**Comment by Crunchmeister1** [comment]
I'm glad you got it sorted. Enjoy the instruments.

**Comment by ghost** [comment]
> 
> Same with the G1000 NXi.... I'm not sure why it wouldn't be working but the default AM one would. Both bezels are sending the exact same commands to Air Manager. 
> 
> 
One thing is sure, barometric pressure numbers only works on AM version. Too bad, yours is nicer!

**Comment by Crunchmeister1** [comment]
> One thing is sure, barometric pressure numbers only works on AM version. Too bad, yours is nicer!

Are you saying the baro adjustment doesn't work for you? Because I'm sitting in a plane using the G1000 right now and having no issues adjusting my baro.

**Comment by ghost** [comment]
Exactly. Everything else seems to work. Everything works on the Am version.

**Comment by Crunchmeister1** [comment]
Odd that it doesn't work for you. Baro setting works for me. Looking at it right now. It's even the same events being sent from the G1000 in both of them - fs2020_event("KOHLSMAN_INC") and fs2020_event("KOHLSMAN_INC").

Are you sure you have the most recent version of our bezel?

**Comment by ghost** [comment]
Yes. I think its dated October.

**Comment by Crunchmeister1** [comment]
Baro works

**Comment by Crunchmeister1** [comment]
I don't know what to tell you man. I'm sitting in the Kodiak right now. Spinning the baro knob switches pressure in the G1000 as it should.

**Comment by Onthemarks** [comment]
I am just getting home. I will check my G1000 Baro using my Knobster.

**Comment by Crunchmeister1** [comment]
Here I am using it with my Knobster.
https://www.youtube.com/watch?v=V3gr7TsopKk

**Comment by Onthemarks** [comment]
Working for me as well with G1000 NXI in Kodiak 100 using Knobster. Not sure what the issue could be.

**Comment by Onthemarks** [comment]
Maybe check your Air Plugin fs2020_log.txt file to see if any clues? When I turn the Alt dial I get the following successful bind to command. 

30-12-2021 12:58:16 INFO SimBusServerProviderPool: Succesfull bind to command "KOHLSMAN_INC"
30-12-2021 12:58:18 INFO SimBusServerProviderPool: Succesfull bind to command "KOHLSMAN_DEC"

**Comment by rob2791** [comment]
I'm going to close this as it's not a real issue. 
@cgytm I just created a Discord server, hop in the troubleshooting chat and we may be able to help you out faster. 
https://discord.gg/fcvbAeAmgQ

**Comment by Crunchmeister1** [comment]
> Working for me as well with G1000 NXI in Kodiak 100 using Knobster. Not sure what the issue could be.

It works for me in every plane I fly. That just happened to be in the Kodiak.  I regularly fly the C172 G1000, Bonanza, Baron, and CIrrus SR22. Never had the baro knob not work. Ever. 

Like I said, it's the exact same events as in the stock AM G1000 operating the baro. There's no reason it shouldn't work from one and not the other.

**Comment by hairy-dog** [comment]
Hmm.   
  
Maybe the barometer settings 'bug' is fixed, but if you are correct, there is another issue.   
  
That isn't the correct spelling of 'successful'.
  

  

  
  
 -- Iain  

  
  
  
  
  
>
